[package]
name = "chuva"
version = "0.1.0"
edition = "2024"

[features]
load = ["dep:netcdf", "dep:jiff"]

[dependencies]
jiff = { workspace = true, optional = true }

proj4rs = "0.1.9"
netcdf = { version = "0.11.1", default-features = false, features = ["static"], optional = true }
